config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /ja|en/ do

    get '/' => 'user/sessions#index'

    namespace :operator do

      get    'sign_in'         => 'sessions#index'
      post   'sign_in'         => 'sessions#create'
      delete 'sign_out'        => 'sessions#destroy'

      resources :users
      resources :vocabularies
    end

    #This is namespace user
    namespace :user do

      get    'sign_in'         => 'sessions#index'
      post   'sign_in'         => 'sessions#create'
      get 'sign_out'        => 'sessions#destroy'

      get '/get_vocabulary_by_lesson' => 'vocabularies#get_vocabulary_by_lesson'

      resources :users
      resources :homes
      resources :vocabularies, only: [:index]
      resources :practices
    end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/operator/user.rb
class Operator::User < ApplicationRecord
    has_secure_password
    validates :nickname, :password, :presence=>true
end

app/models/user.rb
module User
  def self.table_name_prefix
    'user_'
  end
end

app/models/user/exercise.rb
class User::Exercise < ApplicationRecord
  belongs_to :user_lesson, :class_name => 'User::Lesson', inverse_of: :user_exercises
end

app/models/user/grammar.rb
class User::Grammar < ApplicationRecord
  belongs_to :user_lesson, :class_name => 'User::Lesson', inverse_of: :user_grammars
end

app/models/user/lesson.rb
class User::Lesson < ApplicationRecord
  has_many :user_vocabularies, :class_name => 'User::Vocabulary',foreign_key: :user_lessons_id, inverse_of: :user_lesson, dependent: :destroy
  has_many :user_grammars, :class_name => 'User::Grammar', foreign_key: :user_grammars_id, inverse_of: :user_lesson, dependent: :destroy
  has_many :user_exercises, :class_name => 'User::Exercise', foreign_key: :user_exercises_id, inverse_of: :user_lesson, dependent: :destroy
end

app/models/user/user.rb
class User::User < ApplicationRecord
    has_secure_password
    validates :nickname, :email, :password, :presence=>true
    validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } 
end
 

app/models/user/vocabulary.rb
class User::Vocabulary < ApplicationRecord
  belongs_to :user_lesson, :class_name => 'User::Lesson', inverse_of: :user_vocabularies
end

app/controllers/operator/users_controller.rb
class Operator::UsersController < Operator::BaseController
  before_action :set_operator_user, only: [:show, :edit, :update, :destroy]

  # GET /operator/users
  # GET /operator/users.json
  def index
    @operator_users = Operator::User.all
  end

  # GET /operator/users/1
  # GET /operator/users/1.json
  def show
  end

  # GET /operator/users/index
  def new
    @operator_user = Operator::User.new
  end

  # GET /operator/users/1/edit
  def edit
  end

  # POST /operator/users
  # POST /operator/users.json
  def create
    @operator_user = Operator::User.new(operator_user_params)

    respond_to do |format|
      if @operator_user.save
        format.html { redirect_to @operator_user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @operator_user }
      else
        format.html { render :new }
        format.json { render json: @operator_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operator/users/1
  # PATCH/PUT /operator/users/1.json
  def update
    respond_to do |format|
      if @operator_user.update(operator_user_params)
        format.html { redirect_to @operator_user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @operator_user }
      else
        format.html { render :edit }
        format.json { render json: @operator_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operator/users/1
  # DELETE /operator/users/1.json
  def destroy
    @operator_user.destroy
    respond_to do |format|
      format.html { redirect_to operator_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operator_user
      @operator_user = Operator::User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operator_user_params
      params.fetch(:operator_user, {})
    end
end

app/controllers/user/base_controller.rb
class User::BaseController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout 'user/layouts/application'

  include User::SessionsHelper

  before_action :set_locale
  before_action :enforce_user_sign_in

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end

  private
  # I18n.locale をセットする
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < User::BaseController
  def index
  end
end

app/controllers/user/practices_controller.rb
class User::PracticesController < User::BaseController
  def index
  end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < User::BaseController
  layout 'user/layouts/login'
  skip_before_action :enforce_user_sign_in
  def index
  end

  def create
    user = User::User.find_by_nickname(params[:session][:nickname])

    if user && user.authenticate(params[:session][:password])
      flash[:success] = 'Wellcome back !!'
      user_sign_in user
      redirect_to user_homes_path
    else
      flash.now[:error] = "Invalid UserID or password!"
      render action: :new
    end
  end

  def destroy
    user_sign_out if user_signed_in?
    redirect_to '/', success: "Signed out!"
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < User::BaseController
  before_action :set_user_user, only: [:show, :edit, :update, :destroy]

  # GET /user/users
  # GET /user/users.json
  def index
    @user_users = User::User.all
  end

  # GET /user/users/1
  # GET /user/users/1.json
  def show
  end

  # GET /user/users/index
  def new
    @user_user = User::User.new
  end

  # GET /user/users/1/edit
  def edit
  end

  # POST /user/users
  # POST /user/users.json
  def create
    @user_user = User::User.new(user_user_params)

    respond_to do |format|
      if @user_user.save
        format.html { redirect_to @user_user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user_user }
      else
        format.html { render :new }
        format.json { render json: @user_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user/users/1
  # PATCH/PUT /user/users/1.json
  def update
    respond_to do |format|
      if @user_user.update(user_user_params)
        format.html { redirect_to @user_user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_user }
      else
        format.html { render :edit }
        format.json { render json: @user_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user/users/1
  # DELETE /user/users/1.json
  def destroy
    @user_user.destroy
    respond_to do |format|
      format.html { redirect_to user_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_user
      @user_user = User::User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_user_params
      params.fetch(:user_user, {})
    end
end

app/controllers/user/vocabularies_controller.rb
class User::VocabulariesController < User::BaseController
  require 'json'

  def index
    @lesson = User::Lesson.all
  end

  def get_vocabulary_by_lesson
    lesson_id = params[:sltLesson]
    arr_vocabulary = Array.new
    vocabularies = User::Lesson.find(params[:sltLesson]).user_vocabularies
    vocabularies.each do |vocabulary|
      arr_vocabulary.push(
          "word": "#{vocabulary.word}",
          "mean": "#{vocabulary.mean}"
      )
    end
    render json: {
      sltLesson: lesson_id,
      arrVocabulary: arr_vocabulary
    }
  end

end

app/helpers/operator/users_helper.rb
module Operator::UsersHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/practices_helper.rb
module User::PracticesHelper
end

app/helpers/user/sessions_helper.rb
module User::SessionsHelper
  def enforce_user_sign_in
    unless user_signed_in?
      flash[:error] = 'Please sign in.'
      redirect_to user_sign_in_path
    end
  end

  def user_sign_in(user)
    session[:user_user_id] = user.id
  end

  def user_signed_in?
    user_operator_user.present?
  end

  def user_operator_user
    if session[:user_user_id]
      @current_user_user ||= User::User.find_by(id: session[:user_user_id])
    end
  end

  def user_sign_out
    session.delete(:user_user_id)
    @current_user_user = nil
  end

  # Returns the current signed in user (if any)
  def current_user
    if session[:user_user_id]
      @current_user ||= User::User.find_by(id: session[:user_user_id])
    end
  end

  def lesson
    User::Lesson.all
  end
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/helpers/user/vocabularies_helper.rb
module User::VocabulariesHelper
end

app/views/user/layouts/_navigation.html.erb
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <%= image_tag "user/avatar.png" , class:"img-circle", alt:"User Image"%>
      </div>
      <div class="pull-left info">
        <p><%= current_user.nickname %></p>
        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu" data-widget="tree">
      <!--      Home menu-->
      <li>
        <%= link_to user_homes_path do %>
          <i class="fa fa-th"></i>
          <span>Home</span>
        <% end %>
      </li>

      <!--      Lession menu-->
      <li class="treeview">
        <a href="#">
          <i class="fa fa-files-o"></i>
          <span>Grammar</span>
          <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <% lesson.each do |lesson| %>
            <li><a href=""><i class="fa fa-circle-o"></i> <%=lesson.name %></a></li>
          <%end %>
        </ul>
      </li>

      <!--      Vocabulary menu-->
      <li>
        <%= link_to user_vocabularies_path do %>
          <i class="fa fa-pie-chart"></i>
          <span>Vocabulary</span>
        <% end %>
      </li>

      <!--      Part5 menu-->
      <li>
        <%= link_to user_practices_path do %>
          <i class="fa fa-laptop"></i>
          <span>Practice</span>
        <% end %>
      </li>

    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

app/views/user/layouts/_topnavbar.html.erb
<header class="main-header">
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= image_tag "user/avatar.png" , class:"img-circle", alt:"User Image", style: "width:30px"%>&nbsp;&nbsp;
            <span><b><%= current_user.nickname %></b></span>
          </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header">
              <%= image_tag "user/avatar.png" , class:"img-circle", alt:"User Image"%>
              <p>
                Trần Thiện Hòa - Web Developer
                <small>Member since Nov. 2012</small>
              </p>
            </li>
            <!-- Menu Body -->
            <li class="user-body">
              <div class="row">
                <div class="col-xs-4 text-center">
                  <a href="#">Followers</a>
                </div>
                <div class="col-xs-4 text-center">
                  <a href="#">Sales</a>
                </div>
                <div class="col-xs-4 text-center">
                  <a href="#">Friends</a>
                </div>
              </div>
              <!-- /.row -->
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="#" class="btn btn-default btn-flat">Profile</a>
              </div>
              <div class="pull-right">
                <%= link_to "Sign out", user_sign_out_path, :method => :delete, class: "btn btn-default btn-flat" %>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>

  </nav>
</header>

app/views/user/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Toeic</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'user/application', media: 'all'%>
</head>

<body>
  <div class="row">
    <div class="col-md-2 col-xs-2 navigation-menu">
      <%= render 'user/layouts/navigation' %>
    </div>
    <div class="col-md-offset-2 col-xs-offset-2 col-md-10 col-sm-10 col-xs-12 content-content">
      <div class="top">
        <%= render 'user/layouts/topnavbar' %>
      </div>
      <div class="content" >
        <%= yield %>
      </div>
    </div>
  </div>
  <%= javascript_include_tag 'user/application'%>
  <script>
    <%= sanitize custom_bootstrap_flash %>
  </script>
</body>
</html>

app/views/user/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Toeic</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'user/application', media: 'all'%>
  <%= javascript_include_tag 'user/application'%>
</head>

<body>
<div class="container">
  <%= yield %>
</div>

<script>
  <%= sanitize custom_bootstrap_flash %>
</script>
</body>
</html>